### PR TITLE
Create attribute-index online documentation for PBDF demo scheme

### PR DESCRIPTION
**Pull request by rafaelbernard**
https://app.asana.com/0/1171124854073033/1193313449401387

- Add online documentation
- Used attribute-index tool: https://github.com/privacybydesign/attribute-index

https://demo.irma.nz/attribute-index/en/index.html

### CODE REVIEW

**Comment by ehsan-fj** [comment]
The `About` link the doc goes to simple issuer. Is that what we want?

**Comment by ehsan-fj** [comment]
Also there is an issue section in each attribute with a textbox and button to issue the attribute but they don't work actually.

**Comment by rafaelbernard** [comment]
> The `About` link the doc goes to simple issuer. Is that what we want?

This is the behaviour of our 404. Maybe this is time to remove this redirection and just leave a 404 for not found page. I will check if I can change About to the index correctly.

**Comment by rafaelbernard** [comment]
> Also there is an issue section in each attribute with a textbox and button to issue the attribute but they don't work actually.

I think so. The form interacts with they go server. Once the scheme is merged it PBDF scheme, this will work.

**Review by ehsan-fj — APPROVED** [review]

**Pull request merged**
